apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-env
  namespace: task-scheduler
data:
  # API
  GRPC_PORT: "8081"
  METRICS_PORT: "2112"

  # Worker
  WORKER_POOL_SIZE: "10"

  # CockroachDB
  COCKROACHDB_HOST: "cockroachdb"
  COCKROACHDB_PORT: "26257"
  COCKROACHDB_USER: "root"
  COCKROACHDB_PASSWORD: ""
  COCKROACHDB_DATABASE: "scheduler"
  COCKROACHDB_SSLMODE: "disable"

  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
