apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-scheduler
resources:
  - namespace.yaml
  - configmap.yaml
  - redis.yaml
  - cockroachdb.yaml
  - api.yaml
  - worker.yaml
  - envoy-config.yaml
  - gateway.yaml
  - hpa.yaml
